# The default configuration values for this chart
# Default values for mod-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
elasticsearch:
  enabled: true

mysql:
  enabled: true